general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = systemctl --user stop wallpaper.target; loginctl lock-session
    after_sleep_cmd = systemctl --user start wallpaper.target && hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Screen off at 5 minutes
listener {
    timeout = 300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Lock at 15 min
listener {
    timeout = 1500
    on-timeout = loginctl lock-session
}

# Suspend at 30 min
listener {
    timeout = 1800
    on-timeout = loginctl suspend
}
