general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = systemctl --user stop wallpaper.target && loginctl lock-session
    after_sleep_cmd = systemctl --user start wallpaper.target && hyprctl dispatch dpms on
}

# Screen off at 5 minutes
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Lock at 15 minutes
listener {
    timeout = 900
    on-timeout = loginctl lock-session
}

# Suspend at 3 hours
listener {
#    timeout = 1800
    timeout = 10800
    on-timeout = loginctl suspend
}
